[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

[site]
  name = "empilhadeira-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"